name: Release

on:
  push:
    branches:
      - '**'

env:
  BIN_NAME: termusic
  BIN_NAME_SERVER: termusic-server

jobs:
  dist:
    name: Dist
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-gnu

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libasound2-dev libdbus-1-dev pkg-config protobuf-compiler libgstreamer1.0-dev libmpv-dev libunwind-dev

      - name: Build
        run: cargo build --features cover,all-backends,rusty-soundtouch --release --all --target x86_64-unknown-linux-gnu

      - name: Strip binaries
        run: |
          strip target/x86_64-unknown-linux-gnu/release/$BIN_NAME
          strip target/x86_64-unknown-linux-gnu/release/$BIN_NAME_SERVER

      - name: Package
        run: |
          mkdir -p dist
          tar cJf dist/termusic-latest.tar.xz \
            -C target/x86_64-unknown-linux-gnu/release \
            $BIN_NAME $BIN_NAME_SERVER

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/termusic-latest.tar.xz
          tag: latest
          release_name: termusic-latest
          overwrite: true
